// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfoo.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFoo_CfgInitialize(XFoo *InstancePtr, XFoo_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFoo_Start(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL) & 0x80;
    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFoo_IsDone(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFoo_IsIdle(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFoo_IsReady(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFoo_EnableAutoRestart(XFoo *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XFoo_DisableAutoRestart(XFoo *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_AP_CTRL, 0);
}

void XFoo_Set_byte_block_in_offset(XFoo *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_BYTE_BLOCK_IN_OFFSET_DATA, Data);
}

u32 XFoo_Get_byte_block_in_offset(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_BYTE_BLOCK_IN_OFFSET_DATA);
    return Data;
}

void XFoo_Set_byte_x_in_in_offset(XFoo *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_BYTE_X_IN_IN_OFFSET_DATA, Data);
}

u32 XFoo_Get_byte_x_in_in_offset(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_BYTE_X_IN_IN_OFFSET_DATA);
    return Data;
}

void XFoo_Set_byte_y_out_out_offset(XFoo *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_BYTE_Y_OUT_OUT_OFFSET_DATA, Data);
}

u32 XFoo_Get_byte_y_out_out_offset(XFoo *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_BYTE_Y_OUT_OUT_OFFSET_DATA);
    return Data;
}

void XFoo_InterruptGlobalEnable(XFoo *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_GIE, 1);
}

void XFoo_InterruptGlobalDisable(XFoo *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_GIE, 0);
}

void XFoo_InterruptEnable(XFoo *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_IER);
    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_IER, Register | Mask);
}

void XFoo_InterruptDisable(XFoo *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_IER);
    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_IER, Register & (~Mask));
}

void XFoo_InterruptClear(XFoo *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFoo_WriteReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_ISR, Mask);
}

u32 XFoo_InterruptGetEnabled(XFoo *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_IER);
}

u32 XFoo_InterruptGetStatus(XFoo *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFoo_ReadReg(InstancePtr->Bus_a_BaseAddress, XFOO_BUS_A_ADDR_ISR);
}

